name: Worker Images

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      
      - name: Build Worker topology-updater
        uses: docker/build-push-action@v2
        with:
          context: ./workers/topology-updater
          tags: |
            ghcr.io/trafulpool/topology-updater:latest
          push: true
      
      - name: Build Worker tip-notifier
        uses: docker/build-push-action@v2
        with:
          context: ./workers/tip-notifier
          tags: |
            ghcr.io/trafulpool/tip-notifier:latest
          push: true
